# Generated by Django 5.2.4 on 2025-08-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='fas fa-paw', help_text="Font Awesome icon class, e.g. 'fas fa-dog'", max_length=50),
        ),
    ]
