# Generated by Django 3.1 on 2025-08-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petcategory',
            options={'verbose_name_plural': 'Pet Categories'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelTable(
            name='petcategory',
            table='pet_category',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category',
        ),
    ]
