# Generated by Django 5.2.4 on 2025-08-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
